GRANT ALL PRIVILEGES ON DATABASE abanking_sco TO abanking_sco;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO abanking_sco;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO abanking_sco;