/*
 * Copyright (c) 2017 Anzen Soluciones S.A. de C.V.
 * Mexico D.F.
 * All rights reserved.
 *
 * THIS SOFTWARE IS  CONFIDENTIAL INFORMATION PROPIETARY OF ANZEN SOLUCIONES.
 * THIS INFORMATION SHOULD NOT BE DISCLOSED AND MAY ONLY BE USED IN ACCORDANCE THE TERMS DETERMINED BY THE COMPANY ITSELF.
 */
-- this is the actions for an user
CREATE TABLE CCS_ACTIONS (
    ID_ACTION character varying(25) NOT NULL PRIMARY KEY,
    DESCRIPTION character varying(70) NOT NULL  
);
COMMENT ON TABLE CCS_ACTIONS IS 'Contains operations descriptions';
-- this is the actions for an user

-- an user has a role
CREATE TABLE CCS_ROLES(
    ID_ROLE VARCHAR(16) NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(50) NOT NULL
);
COMMENT ON TABLE CCS_ROLES IS 'A role is a set of actions.';
-- an user has a role

-- this table contains all users
CREATE TABLE CCS_USERS(
    ID_USER VARCHAR(255) NOT NULL PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    LAST_NAME_1 VARCHAR(30) NOT NULL,
    LAST_NAME_2 VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL DEFAULT TRUE,
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    ERROR_COUNT_FAILED_LOGINS INTEGER DEFAULT 3 NOT NULL,
    FIRST_TIME BOOLEAN DEFAULT true NOT NULL
);
COMMENT ON TABLE CCS_USERS IS 'Users that operate and administrate the Back Office.';
COMMENT ON COLUMN CCS_USERS.ID_USER IS 'Identifier of the user, kind of nickname';
COMMENT ON COLUMN CCS_USERS.NAME IS 'Name of the user';
COMMENT ON COLUMN CCS_USERS.LAST_NAME_1 IS 'First last name of the user, in Mexico is fathers last name.';
COMMENT ON COLUMN CCS_USERS.LAST_NAME_2 IS 'Second last name of the user, in Mexico is mothers last name.';
COMMENT ON COLUMN CCS_USERS.EMAIL IS 'email address';
COMMENT ON COLUMN CCS_USERS.ENABLED IS 'Flag that indicates wheter the user is enable (1) or disable (0)';

-- this table contains the user password 
CREATE TABLE CCS_CREDENTIALS(
    ID_USER VARCHAR(255) NOT NULL PRIMARY KEY,
    SALT VARCHAR(256) NOT NULL,
    HASH VARCHAR(256) NOT NULL,

    CONSTRAINT FK_CREDENTIALS_USERS FOREIGN KEY (ID_USER) REFERENCES CCS_USERS(ID_USER)
);
COMMENT ON TABLE CCS_CREDENTIALS IS 'Stored credentials of the users';

-- this table is a relational
CREATE TABLE CCS_ROLE_ACTIONS(
    ID_ROLE VARCHAR(16) NOT NULL,
    ID_ACTION VARCHAR(25) NOT NULL,

    CONSTRAINT PK_ROLE_ACTIONS PRIMARY KEY (ID_ROLE, ID_ACTION),
    CONSTRAINT FK_ROLE_ACTIONS_ROLES FOREIGN KEY (ID_ROLE) REFERENCES CCS_ROLES(ID_ROLE),
    CONSTRAINT FK_ROLE_ACTIONS_ACTIONS FOREIGN KEY (ID_ACTION) REFERENCES CCS_ACTIONS(ID_ACTION)
);

-- this table is a relational
CREATE TABLE CCS_USER_ROLES(
    ID_USER VARCHAR(255) NOT NULL,
    ID_ROLE VARCHAR(16) NOT NULL,
    
    CONSTRAINT PK_USER_ROLES PRIMARY KEY (ID_USER, ID_ROLE),
    CONSTRAINT FK_USER_ROLES_USERS FOREIGN KEY (ID_USER) REFERENCES CCS_USERS(ID_USER),
    CONSTRAINT FK_USER_ROLES_ROLES FOREIGN KEY (ID_ROLE) REFERENCES CCS_ROLES(ID_ROLE)
);

-- this table contains logs for sessions
CREATE TABLE CCS_USER_LOG(
    ID_USER VARCHAR(255) NOT NULL,
    LOG_TIME TIMESTAMP NOT NULL,
    ID_ACTION VARCHAR(25) NOT NULL,

    CONSTRAINT PK_USER_LOG PRIMARY KEY (ID_USER, LOG_TIME),
    CONSTRAINT FK_USER_LOG_ACTION FOREIGN KEY (ID_ACTION) REFERENCES CCS_ACTIONS (ID_ACTION)
);

-- this table contains the card bin
CREATE TABLE CAT_BINES(
    BIN NUMERIC(6,0) PRIMARY KEY, 
    NATURALEZA NUMERIC(2,0)
);

