version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  abankingcore:
    image: abanking_core.1.0.1
    volumes:
      - ./core/:/usr/src/app/core/
    ports:
      - 8090:8090
    links:
      - mongo
      - redis
      - rabbitmq
  #nginx:
  #  image: nginx:alpine
  #  volumes:
  #    - ./nginx/:/etc/nginx/
  #  ports:
  #    - 80:80
  #  environment:
  #    - NGINX_PORT=80
  #  links:
  #    - abankingcore
  postgres:
    image: postgres
    volumes:
      - ./user_component/postgres:/docker-entrypoint-initdb.d
      - ./user_component/sql:/tmp
    ports:
      - 5431:5432
  scotiausercomponent:
    image: scotialeap_user_component
    volumes:
      - ./user_component/config:/usr/src/app/userComponent
      - ./user_component/lib:/usr/src/app/lib
    ports:
      - 8184:8184
    links:
      - postgres
  backoffice_activation_code:
    image: activation_code_backoffice
    volumes:
      - ./backoffice_activation_code:/usr/src/app/backofficeActivationCode
    ports:
      - 8089:8089
    links:
      - postgres
  backoffice_admin_rest:
    image: backoffice_admin_rest_scotia
    volumes:
      - ./backoffice_admin_rest:/usr/src/app/backofficeAdminRest
    ports:
      - 8186:8186
    depends_on:
      - mongo
      - postgres
      - rabbitmq
    links:
      - mongo
      - postgres
      - rabbitmq

